import '../../models/product_model.dart';

class ProductCatalog {
  static const List<String> defaultCategories = [
    'Books',
    'Stationery',
    'School Supplies',
    'Uniforms',
    'Learning Aids',
    'Art & Craft',
    'Seeds',
    'Fertilizer',
    'Crop Protection',
    'Equipment',
    'Animal Feed',
    'Tools',
  ];

  static const List<String> defaultSuppliers = [
    'Longhorn Publishers',
    'Oxford University Press (EA)',
    'JKF Publishers',
    'Moran Publishers',
    'Stationery Plus',
    'AgriGrow Ltd',
    'FertCo',
    'AquaFlex',
    'GreenHarvest',
  ];

  static const List<String> defaultUnits = [
    'pieces',
    'copies',
    'packs',
    'sets',
    'shrink',
    'cases',
    'kg',
    'litres',
    'boxes',
    'reams',
  ];

  static const List<String> gradeLevels = [
    'Pre-Primary',
    'Grade 1',
    'Grade 2',
    'Grade 3',
    'Grade 4',
    'Grade 5',
    'Grade 6',
    'Grade 7',
    'Grade 8',
    'Form 1',
    'Form 2',
    'Form 3',
    'Form 4',
    'University',
    'General',
  ];

  static const List<String> subjects = [
    'Mathematics',
    'English',
    'Kiswahili',
    'Science',
    'Social Studies',
    'Religious Studies',
    'Agriculture',
    'Home Science',
    'Computer Studies',
    'Business Studies',
    'Geography',
    'History',
    'CRE',
    'IRE',
    'French',
    'General',
  ];

  static const List<String> languages = [
    'English',
    'Kiswahili',
    'French',
    'Arabic',
    'Bilingual',
  ];
}

List<Product> defaultCatalogProducts() {
  return [
    Product(
      id: 'p1',
      name: 'Understanding Mathematics Grade 5',
      sku: 'LH-MAT-G5',
      description: 'Approved textbook for upper primary mathematics.',
      supplierId: 'sup1',
      supplierName: 'Longhorn Publishers',
      category: 'Books',
      unitPrice: 650.0,
      wholesalePrice: 520.0,
      unit: 'copies',
      currentStock: 240,
      minStock: 50,
      maxStock: 1000,
      author: 'J.M. Otieno',
      publisher: 'Longhorn Publishers',
      isbn: '9789966012345',
      edition: '3rd Edition',
      gradeLevel: 'Grade 5',
      subject: 'Mathematics',
      language: 'English',
      pageCount: 288,
    ),
    Product(
      id: 'p2',
      name: 'Oxford English Student Book 4',
      sku: 'OUP-ENG-G4',
      supplierId: 'sup2',
      supplierName: 'Oxford University Press (EA)',
      category: 'Books',
      unitPrice: 720.0,
      wholesalePrice: 600.0,
      unit: 'copies',
      currentStock: 180,
      minStock: 40,
      maxStock: 800,
      author: 'Tom Smith',
      publisher: 'Oxford University Press',
      isbn: '9780198345671',
      edition: '2nd Edition',
      gradeLevel: 'Grade 4',
      subject: 'English',
      language: 'English',
      pageCount: 144,
    ),
    Product(
      id: 'p3',
      name: 'JKF Secondary Biology Form 3',
      sku: 'JKF-BIO-F3',
      supplierId: 'sup3',
      supplierName: 'JKF Publishers',
      category: 'Books',
      unitPrice: 980.0,
      wholesalePrice: 820.0,
      unit: 'copies',
      currentStock: 90,
      minStock: 30,
      maxStock: 500,
      author: 'P. Wanyama',
      publisher: 'JKF',
      isbn: '9789966998877',
      edition: '1st Edition',
      gradeLevel: 'Form 3',
      subject: 'Science',
      language: 'English',
      pageCount: 360,
    ),
    Product(
      id: 'p4',
      name: 'Moran Kiswahili Grade 6',
      sku: 'MOR-KIS-G6',
      supplierId: 'sup4',
      supplierName: 'Moran Publishers',
      category: 'Books',
      unitPrice: 540.0,
      wholesalePrice: 430.0,
      unit: 'copies',
      currentStock: 12,
      minStock: 30,
      maxStock: 600,
      author: 'A. Mwangi',
      publisher: 'Moran',
      isbn: '9789966555111',
      gradeLevel: 'Grade 6',
      subject: 'Kiswahili',
      language: 'Kiswahili',
      pageCount: 196,
    ),
    Product(
      id: 'p5',
      name: 'Exercise Book 200pg (Pack of 5)',
      sku: 'STN-EXB-200',
      supplierId: 'sup5',
      supplierName: 'Stationery Plus',
      category: 'Stationery',
      unitPrice: 350.0,
      wholesalePrice: 280.0,
      unit: 'packs',
      currentStock: 320,
      minStock: 80,
      maxStock: 1500,
    ),
    Product(
      id: 'p6',
      name: 'Geometric Set (Maths Instruments)',
      sku: 'STN-GEO-SET',
      supplierId: 'sup5',
      supplierName: 'Stationery Plus',
      category: 'School Supplies',
      unitPrice: 420.0,
      wholesalePrice: 330.0,
      unit: 'sets',
      currentStock: 0,
      minStock: 25,
      maxStock: 400,
    ),
    Product(
      id: 'p7',
      name: 'School Backpack (Large)',
      sku: 'SPL-BP-LG',
      supplierId: 'sup5',
      supplierName: 'Stationery Plus',
      category: 'School Supplies',
      unitPrice: 1800.0,
      wholesalePrice: 1450.0,
      unit: 'pieces',
      currentStock: 60,
      minStock: 15,
      maxStock: 300,
    ),
    Product(
      id: 'p8',
      name: 'A4 Printing Paper Ream',
      sku: 'STN-A4-REAM',
      supplierId: 'sup5',
      supplierName: 'Stationery Plus',
      category: 'Stationery',
      unitPrice: 580.0,
      wholesalePrice: 480.0,
      unit: 'reams',
      currentStock: 145,
      minStock: 30,
      maxStock: 500,
    ),
  ];
}